// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ggxinfypwzzzntcrnlle.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdneGluZnlwd3p6em50Y3JubGxlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQxNzU1NDksImV4cCI6MjA2OTc1MTU0OX0.Op0sowVwQQgXe-TnKQw7c_QCYthrAYFk8lIsEImrZ_M";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});